###
#   application Settings
###
org.productreviews.service:
 cache:
  allproducts.expiry: 5
 logPath: /opt/products_review/log
 logging:
  level:
   org.springframework.web: INFO
  pattern:
   file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
   
###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:mem:productreviews-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

###
#   SPRING Settings
###        
management:
 port: 8081
 context-path: /manage
 security:
  enabled: false
  roles: SUPERUSER

security:
 basic:
  enabled: true
  path: /manage
 user:
  name: admin
  password: adminaccess
  
server:
 port: 8080
 application:
  name: productsreview
 tomcat:
  accesslog:
   directory: /opt/products_review/log/access/
   enabled: true        
        